name: ASTR 480 Autograder

on:
  - push
  - workflow_dispatch

permissions:
  actions: read
  contents: read

jobs:
  autograding:
    name: Autograding

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install -e .

      - name: Test with pytest
        run: |
          pip install pytest pytest-mock pytest-sugar
          pytest
